set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/env bash
    /usr/bin/ajust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/usr/share/ajust/99-custom.just"
